### PR TITLE
added support to register singletons programmatically

### PR DESCRIPTION
**Pull request by pboechat**
I needed to inject some objects that were built by another API in a XML context and couldn't find a clean way to do it. The only way I found around this issue was exporting them as global names and importing with "member-name". For instance:

<component id="my_object_build_by_other_api"
    dotted-name="my_module"
    member-name="my_object_built_by_another_api_exposed_as_a_global_name" />

That felt like cheating.

So, instead, I suggest something like:

my_assembler.register_singleton("my_object_build_by_other_api", my_object_build_by_other_api)

### CODE REVIEW

**Comment by mzipay** [comment]
Hi pboechat,

I'm hesitant to add a method such as register_singleton because it blurs the lines of responsibility between Context/XMLContext and Assembler.  The context's job is to describe _how_ the component objects get created; the assembler's job is to follow those "recipes" and support appropriate lifecycle methods by component type.

I'd like to avoid adding utility methods to Assembler that circumvent object creation recipes, particularly for component types like singleton that support lifecycle methods. For example, in your proposed register_singleton method, there's no clear way I can see to support after_inject/before_clear lifecycle methods without duplicating complexity that's already accounted for in the context description of such a component.

I do agree that exporting global names from a module created specifically for that purpose seems like "cheating," though.

Could you describe how the 3rd party API is used to create these objects, hopefully along with a code example? Aglyph is designed to support many variations of object creation; I may be able to suggest a clean alternative that does not require modifying Assembler and does not require that you create any extra modules.

Thanks!

(FWIW, the factory-name and member-name support was added _specifically_ to address the use case you're describing. I've encountered only a few edge cases that can't be handled cleanly. Also, Aglyph is quite capable of injecting dependencies into 3rd party objects, as well as using 3rd party objects _as_ dependencies, without requiring that the 3rd party source code be modified. Have you looked at the possibility of describing these external API objects as components in Aglyph's context? They could then be injected via reference like any other application component.)

**Comment by pboechat** [comment]
The API I'm talking about is an entity system implemented in C++ that has with a Python interface. The objects I'm referring to are entities that can only be built via static factory methods. I could certainly use those factory methods to build entities inside Aglyph but DI is being adopted in small steps and I can't afford changing the way those entities are created now (it's a maintenance project and the code base is huge).
I don't like the idea of exposing global names and I also don't think register_singleton is a neat solution, but I totally understand you don't want to add this workaround in Aglyph.
I'll consider discarding my fork and joining your branch as soon I reach the point where entities can be created with a factory method :)

**Comment by mzipay** [comment]
>> The objects I'm referring to are entities that can only be built via static factory methods.

Aglyph supports this object creation pattern directly:

```
<component
   id="my-object"
   dotted-name="external.api"
   factory-name="ObjectFactory.create_object"
   strategy="singleton"
>
   <init>...</init>
   <attributes>...</attributes>
</component>
```

Here we have a module `external.api` that contains a class `ObjectFactory` that has a static factory method named `create_object`.

Calling _assembler.assemble("my-object")_ will:

1. Check to see if the singleton "my-object" has already been assembled, and return it if that is the case. Otherwise...
2. Import the ObjectFactory class from the external.api module
3. Call the static create_object method to create the object (injecting anything specified by `<init>`).
4. Inject anything specified by `<attributes>`.
5. Cache the assembled object in the internal singleton cache.

If external.api were implemented in Python, it might look like this:

```
# external.api
class ObjectFactory:
    @staticmethod
    def create_object(...):
        # create the obj
        return obj
```

(Note that the `<component>` definition above also works if create_object is a `@classmethod`.)

In another variation, the external.api module may expose a factory _function_ in the module namespace.  This, too, is directly supported:

```
<component
   id="my-object"
   dotted-name="external.api"
   factory-name="create_object_function"
   strategy="singleton"
>
   <init>...</init>
   <attributes>...</attributes>
</component>
```

If none of these examples solve your problem, would you mind providing a code snippet illustrating how these objects get created in your application? At the very least, it may help me add new features to support your use case directly.

**Comment by pboechat** [comment]
Ok, I can use those factory methods to create objects inside Aglyph. What I
can't do is change the piece of code where those objects are created now
because they are too many and they have very complex creation logic that
would also need to be refactored. I can only afford implementing DI in
small steps, like implementing DI in a small sub-system of the entire
system. Again: It's not a coding issue, it's simply impracticable to change
the entire system right now :)


2016-09-14 16:40 GMT+02:00 Matthew Zipay <notifications@github.com>:

**Comment by mzipay** [comment]
OK, well I'm glad you at least have a path forward. For what it's worth, I have changes coming in release 3.0.0 (which should be soon... I'm finalizing the test suites now) that support some additional object creation patterns like bound method factories.

Also, I have one request - would you mind sharing the Python version, implementation (CPython, Jython, etc.), and platform/OS where you're using Aglyph? This helps me in making sure the test suites are exhaustive. Thanks!

**Pull request closed without merging**
